In [8]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.2.6)
Requirement already satisfied: scipy>=1.10.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.10.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
from sklearn.linear_model import LinearRegression

In [15]:
import pandas as pd

In [52]:
df = pd.read_csv("C:/Users/user/Downloads/financial_regression.csv")

In [43]:
df.head(5)

,date,sp500 open,sp500 high,sp500 low,sp500 close,sp500 volume,sp500 high-low,nasdaq open,nasdaq high,nasdaq low,...,palladium high,palladium low,palladium close,palladium volume,palladium high-low,gold open,gold high,gold low,gold close,gold volume
0,2010-01-14,114.49,115.14,114.42,114.93,115646960.0,0.72,46.26,46.520,46.22,...,45.02,43.86,44.84,364528.0,1.16,111.51,112.37,110.79,112.03,18305238.0
1,2010-01-15,114.73,114.84,113.20,113.64,212252769.0,1.64,46.46,46.550,45.65,...,45.76,44.40,45.76,442210.0,1.36,111.35,112.01,110.38,110.86,18000724.0
2,2010-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010-01-19,113.62,115.13,113.59,115.06,138671890.0,1.54,45.96,46.640,45.95,...,47.08,45.70,46.94,629150.0,1.38,110.95,111.75,110.83,111.52,10467927.0
4,2010-01-20,114.28,114.45,112.98,113.89,216330645.0,1.47,46.27,46.604,45.43,...,47.31,45.17,47.05,643198.0,2.14,109.97,110.05,108.46,108.94,17534231.0

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3904 entries, 0 to 3903
Data columns (total 47 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                3904 non-null   object
 1   sp500 open          3719 non-null   float64
 2   sp500 high          3719 non-null   float64
 3   sp500 low           3719 non-null   float64
 4   sp500 close         3719 non-null   float64
 5   sp500 volume        3719 non-null   float64
 6   sp500 high-low      3719 non-null   float64
 7   nasdaq open         3719 non-null   float64
 8   nasdaq high         3719 non-null   float64
 9   nasdaq low          3719 non-null   float64
 10  nasdaq close        3719 non-null   float64
 11  nasdaq volume       3719 non-null   float64
 12  nasdaq high-low     3719 non-null   float64
 13  us_rates_%          176 non-null    float64
 14  CPI                 176 non-null    float64
 15  usd_chf             3694 non-null   float64
 16  eur_usd             3694 non-null   float64
 17  GDP                 57 non-null     float64
 18  silver open         3719 non-null   float64
 19  silver high         3719 non-null   float64
 20  silver low          3719 non-null   float64
 21  silver close        3719 non-null   float64
 22  silver volume       3719 non-null   float64
 23  silver high-low     3719 non-null   float64
 24  oil open            3719 non-null   float64
 25  oil high            3719 non-null   float64
 26  oil low             3719 non-null   float64
 27  oil close           3719 non-null   float64
 28  oil volume          3719 non-null   float64
 29  oil high-low        3719 non-null   float64
 30  platinum open       3719 non-null   float64
 31  platinum high       3719 non-null   float64
 32  platinum low        3719 non-null   float64
 33  platinum close      3719 non-null   float64
 34  platinum volume     3719 non-null   float64
 35  platinum high-low   3719 non-null   float64
 36  palladium open      3719 non-null   float64
 37  palladium high      3719 non-null   float64
 38  palladium low       3719 non-null   float64
 39  palladium close     3719 non-null   float64
 40  palladium volume    3719 non-null   float64
 41  palladium high-low  3719 non-null   float64
 42  gold open           3719 non-null   float64
 43  gold high           3719 non-null   float64
 44  gold low            3719 non-null   float64
 45  gold close          3719 non-null   float64
 46  gold volume         3719 non-null   float64
dtypes: float64(46), object(1)
memory usage: 1.4+ MB

In [53]:
df = df.drop(df.columns[0:43], axis=1)

In [56]:
df = df.dropna()

In [57]:
df.head(10)

    gold high  gold low  gold close  gold volume
0      112.37    110.79     112.030   18305238.0
1      112.01    110.38     110.860   18000724.0
3      111.75    110.83     111.520   10467927.0
4      110.05    108.46     108.940   17534231.0
5      108.78    106.61     107.370   25747831.0
6      107.68    106.01     107.170   24209966.0
7      107.72    107.07     107.480   13170442.0
8      107.99    106.75     107.560   12274165.0
9      108.80    106.16     106.528   18991219.0
10     107.23    105.18     106.480   16792253.0

In [58]:
y=df[["gold close"]]
x=df[["gold low","gold high"]]

In [59]:
l = LinearRegression()
model = l.fit(x,y) #y=ax+b

In [66]:
model.predict([[110.79,112.37]]) #input verilir output alınır

C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[111.559797]])

In [62]:
model.score(x,y)

0.9997006770585023

In [64]:
model.coef_ #katsayı

array([[0.53032388, 0.47072521]])

In [65]:
model.intercept_ #sabit değişken

array([-0.09017803])

In [70]:
#datada numeric olmasına dikkat et!!
df2 = pd.read_csv("C:/Users/user/Downloads/financial_regression.csv")
df2.head()

,date,sp500 open,sp500 high,sp500 low,sp500 close,sp500 volume,sp500 high-low,nasdaq open,nasdaq high,nasdaq low,...,palladium high,palladium low,palladium close,palladium volume,palladium high-low,gold open,gold high,gold low,gold close,gold volume
0,2010-01-14,114.49,115.14,114.42,114.93,115646960.0,0.72,46.26,46.520,46.22,...,45.02,43.86,44.84,364528.0,1.16,111.51,112.37,110.79,112.03,18305238.0
1,2010-01-15,114.73,114.84,113.20,113.64,212252769.0,1.64,46.46,46.550,45.65,...,45.76,44.40,45.76,442210.0,1.36,111.35,112.01,110.38,110.86,18000724.0
2,2010-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010-01-19,113.62,115.13,113.59,115.06,138671890.0,1.54,45.96,46.640,45.95,...,47.08,45.70,46.94,629150.0,1.38,110.95,111.75,110.83,111.52,10467927.0
4,2010-01-20,114.28,114.45,112.98,113.89,216330645.0,1.47,46.27,46.604,45.43,...,47.31,45.17,47.05,643198.0,2.14,109.97,110.05,108.46,108.94,17534231.0

In [71]:
pd.get_dummies(df2,columns=["palladium high-low"]) 
#bu saçma örnek fakat palladşiumun fiyatlarını vermeden, hangi değerler varsa yeni columnlar oluşturur ve 1 ve 0 hibi (t veya f) tutar. genellikle object stringler için güzel

,date,sp500 open,sp500 high,sp500 low,sp500 close,sp500 volume,sp500 high-low,nasdaq open,nasdaq high,nasdaq low,...,palladium high-low_19.50999999999999,palladium high-low_20.100000000000023,palladium high-low_20.41,palladium high-low_24.149999999999977,palladium high-low_26.093400000000003,palladium high-low_27.06,palladium high-low_27.96720000000002,palladium high-low_32.459900000000005,palladium high-low_37.88,palladium high-low_45.392300000000006
0,2010-01-14,114.49,115.1400,114.4200,114.93,115646960.0,0.7200,46.26,46.520,46.2200,...,False,False,False,False,False,False,False,False,False,False
1,2010-01-15,114.73,114.8400,113.2000,113.64,212252769.0,1.6400,46.46,46.550,45.6500,...,False,False,False,False,False,False,False,False,False,False
2,2010-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
3,2010-01-19,113.62,115.1300,113.5900,115.06,138671890.0,1.5400,45.96,46.640,45.9500,...,False,False,False,False,False,False,False,False,False,False
4,2010-01-20,114.28,114.4500,112.9800,113.89,216330645.0,1.4700,46.27,46.604,45.4300,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3899,2024-10-17,585.91,586.1200,582.1600,582.35,34393714.0,3.9600,496.44,496.490,491.1901,...,False,False,False,False,False,False,False,False,False,False
3900,2024-10-18,584.07,585.3900,582.5800,584.59,37416801.0,2.8100,494.06,495.570,493.3000,...,False,False,False,False,False,False,False,False,False,False
3901,2024-10-21,583.85,584.8500,580.6001,583.63,36439010.0,4.2499,493.25,496.230,491.3100,...,False,False,False,False,False,False,False,False,False,False
3902,2024-10-22,581.05,584.5000,580.3800,583.32,34183835.0,4.1200,492.73,497.445,491.9700,...,False,False,False,False,False,False,False,False,False,False
3903,2024-10-23,581.26,581.7086,574.4150,577.99,47444991.0,7.2936,493.59,494.250,485.0500,...,False,False,False,False,False,False,False,False,False,False